facilityId: 289f3319-ec7d-4880-b82a-f5bd857f7965 # Zeist
timezone: Europe/Amsterdam
maxSuspendSeconds: 100 # Max time to suspend 
matchers:
  - eventTypeId: 351ed3dc-a1b6-4569-89bc-2bfb54dfb417 # Hyrocks
  - eventTypeId: 04ac201c-500e-4e98-b515-ab70748f2bc5 # Kickboxing
    day: 2
    hour: 18
  - eventTypeId: 93331919-6ff5-4f54-b9c8-26a05880f3b7 # HIIT Athletic
    day: 4
    hour: 7
mywellness:
  appId: EC1D38D7-D359-48D0-A60C-D8C0B8FB9DF9
  client: enduserweb
  clientversion: 1.13.10-1629,enduserweb